
ex_compile: ex_compile.c
	gcc -Wall -o ex_compile ex_compile.c `pkg-config --cflags --libs glib-2.0`
word_count: word_count.c
	gcc -Wall -o word_count word_count.c `pkg-config --cflags --libs glib-2.0`